- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart guac-web
  ansible.builtin.systemd:
    name: guac-web
    state: restarted

- name: Restart guac-cloudflared
  ansible.builtin.systemd:
    name: guac-cloudflared
    state: restarted
  when: app_guac_cf_env.stat.exists | default(false) or app_guac_cloudflared_token | length > 0
